
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springBoot
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true

jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  typeAliasesPackage: com.**.bean
#配置缓存和session存储方式，默认ehcache,可选redis
cacheType: ehcache



